"""
Pydantic schemas for the FastAPI bug tracker application.

This module defines request and response schemas for API endpoints.
These use Pydantic models for validation and serialization.

Schemas:
- IssueCreate: Schema for creating a new issue
- IssueResponse: Schema for returning an issue from the API
"""

from typing import Literal, Optional

from pydantic import BaseModel, Field


class IssueCreate(BaseModel):
    """
    Schema for creating a new issue.

    This schema is used for request validation when creating issues.
    The `id` field is auto-generated by the database, so it's not included here.

    Attributes:
        title: Brief title or summary of the issue (required, non-empty)
        description: Detailed description of the issue (optional)
        priority: Priority level of the issue (required)
                  Expected values: "Low", "Medium", "High"
        status: Current status of the issue (optional, defaults to "Open")
                Expected values: "Open", "In Progress", "Closed"
    """

    # Required field with validation - cannot be empty or whitespace only
    title: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Brief title or summary of the issue"
    )

    # Optional field for detailed description
    description: Optional[str] = Field(
        None,
        max_length=5000,
        description="Detailed description of the issue"
    )

    # Required priority field - only accepts specified values
    priority: Literal["Low", "Medium", "High"] = Field(
        ...,
        description="Priority level: Low, Medium, High"
    )

    # Optional status field with default value - only accepts specified values
    status: Optional[Literal["Open", "In Progress", "Closed"]] = Field(
        "Open",
        description="Issue status: Open, In Progress, Closed"
    )


class IssueResponse(BaseModel):
    """
    Schema for returning an issue from the API.

    This schema includes the `id` field which is provided by the database.
    Used for serializing Issue ORM objects to JSON responses.

    Attributes:
        id: Unique identifier for the issue
        title: Brief title or summary of the issue
        description: Detailed description of the issue
        priority: Priority level of the issue
        status: Current status of the issue

    Config:
        from_attributes: Enables ORM mode for reading data from SQLAlchemy models
    """

    # Issue identifier - auto-generated
    id: int = Field(
        ...,
        description="Unique issue identifier"
    )

    # Issue title
    title: str = Field(
        ...,
        description="Brief title or summary of the issue"
    )

    # Optional description
    description: Optional[str] = Field(
        None,
        description="Detailed description of the issue"
    )

    # Priority level - only accepts specified values
    priority: Literal["Low", "Medium", "High"] = Field(
        ...,
        description="Priority level: Low, Medium, High"
    )

    # Issue status - only accepts specified values
    status: Literal["Open", "In Progress", "Closed"] = Field(
        ...,
        description="Issue status: Open, In Progress, Closed"
    )

    # Enable reading data from SQLAlchemy ORM models
    model_config = {
        "from_attributes": True
    }


class IssueUpdate(BaseModel):
    """
    Schema for updating an existing issue.

    This schema has all fields as optional, allowing partial updates.
    Only provided fields will be updated in the database.

    Attributes:
        title: Brief title or summary of the issue (optional)
        description: Detailed description of the issue (optional)
        priority: Priority level of the issue (optional)
                  Expected values: "Low", "Medium", "High"
        status: Current status of the issue (optional)
                Expected values: "Open", "In Progress", "Closed"
    """

    # Optional title field
    title: Optional[str] = Field(
        None,
        min_length=1,
        max_length=255,
        description="Brief title or summary of the issue"
    )

    # Optional description field
    description: Optional[str] = Field(
        None,
        max_length=5000,
        description="Detailed description of the issue"
    )

    # Optional priority field - only accepts specified values
    priority: Optional[Literal["Low", "Medium", "High"]] = Field(
        None,
        description="Priority level: Low, Medium, High"
    )

    # Optional status field - only accepts specified values
    status: Optional[Literal["Open", "In Progress", "Closed"]] = Field(
        None,
        description="Issue status: Open, In Progress, Closed"
    )
